### ISSUE TITLE
Spacing in publications list <li> is uneven and mobile view doesn't look great

### ISSUE THREAD

**Issue by sourishg** [castacks/castacks.github.io#39]
![Screenshot from 2020-10-23 13-40-42](https://user-images.githubusercontent.com/1478154/97036172-6f519680-1535-11eb-9866-73ca14a784f1.png)

I tried looking at this issue a lot to fix the spacing between the `<li>` tags and the content but couldn't come up with a solution. In my opinion, the code is a bit ugly for this and needs fixing. The buttons seem to be aligned but not the text.

The list number is not generated by the `<li>` (which I think it should be that way) and instead, the content lies inside a nested `<span>` and `<div>` tag. Please inspect the element to see it while fixing this issue.

**Comment by bradygm** [comment]
@jfkeller You worked on this for a while, right? Should we just close this, or should someone else give it a try?

**Comment by jfkeller** [comment]
I fixed the issue related to the `@phdthesis` but not the general spacing issue which causes things to be misaligned when there are long titles or author lists. Also the alignment of the text is effected by the number of digits in the citation number. Fixing this would require modifying whatever is generating the html, instead of just modifying the input to the generator which is what I did to fix the phdthesis issue. I guess its not too noticeable, so maybe we could close it unless someone wants to write a new generator or figure out how to modify the current one.
